# Numpy

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.6 MB 16.8 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.6 MB 16.8 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 16.8 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 16.2 MB/s eta 0:00:00


In [2]:
import numpy as np

In [4]:
# 1D array

array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print(type(array_1d))

1D Array:
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# turn into 2D array
array_2d = array_1d.reshape(1, 5) # reshape to 1 row, 5 columns
array_2d # output [[1, 2, 3, 4, 5]] 2d array

array([[1, 2, 3, 4, 5]])

In [7]:
type(array_2d) # check type of array_2d

numpy.ndarray

In [9]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]]) # create a 2D array directly

print("2D Array:")
print(array_2d)
print(array_2d.shape) # check shape of array_2d

2D Array:
[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
# inbuilt function to create 2D array

array_2d = np.arange(1, 10).reshape(3, 3) # create a 3x3 array with values from 1 to 9
print("2D Array using arange:")
print(array_2d)
print(f"Array is {array_2d.ndim} diemensional")
print(f"Array is of {array_2d.size} size")
print(f"Array is of {array_2d.dtype} type")

2D Array using arange:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array is 2 diemensional
Array is of 9 size
Array is of int64 type


In [12]:
np.ones((3, 3)) # create a 3x3 array filled with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3) # create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.zeros((3, 3)) # create a 3x3 array filled with zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Numpy vectorized operations

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([20,30,40,50,60])

# element-wise addition
arr3 = arr1 + arr2

print("Element-wise addition:")
print(arr3) # output [21, 32, 43, 54, 65]

# element-wise multiplication
arr4 = arr1 * arr2
print("Element-wise multiplication:")
print(arr4) # output [20, 60, 120, 200, 300]

Element-wise addition:
[21 32 43 54 65]
Element-wise multiplication:
[ 20  60 120 200 300]


In [20]:
# Unviersal functions

arr5 = np.array([1, 2, 3, 4, 5])

print("Square root of each element:")
print(np.sqrt(arr5))

print("Exponential of each element:")
print(np.exp(arr5))

print("Logarithm of each element:")
print(np.log(arr5))

Square root of each element:
[1.         1.41421356 1.73205081 2.         2.23606798]
Exponential of each element:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm of each element:
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [22]:
# Array slicing and indexing

array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(array2D)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
array2D[0][2]

np.int64(3)

In [ ]:
array2D[0:,1:] # slicing the array to get all rows and columns from 1 to end


array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array2D[0:2,0:1] # slicing the array to get first two rows and first column

array([[1],
       [4]])

In [32]:
array2D[1:,0:2]

array([[4, 5],
       [7, 8]])

In [33]:
# practical example
# Normalization of data

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original Data:")

mean = np.mean(data, axis=0) # mean of each column
print(mean)
std  = np.std(data, axis=0) # standard deviation of each column
print(std)


Original Data:
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


In [34]:
# Logical operations

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(data > 5) # check which elements are greater than 5
print(data[data > 5]) # get elements greater than 5
print(data[data > 5].sum()) # sum of elements greater than 5

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
30
